version: '3.4'
services:
  mongo-container:
    image: mongo:4.2
    network_mode: host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
      
  nodejs-app:
    image: node:latest
    network_mode: host
    container_name: nodejs-app
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongo-container
    command: bash -c "npm install && node index.js"
